theme: jekyll-theme-midnight
title: "Chess Openings Learning"
description: "This site will help you find the chess Openings for you and how to play them. "
gitorg: "https://github.com/jm1021/leuck_reunion"
google_analytics:
